language: rust

os:
  - linux


before_install:
  - rustup component add clippy rustfmt
  - rustup override set nightly


install:
  - cargo clippy -- -Wclippy::all
  - cargo fmt -- --check
  - cargo run -- dump -a
