language: rust

os:
  - linux


before_install:
  - rustup toolchain add nightly
  - rustup override set nightly
  - rustup component add clippy rustfmt


install:
  - cargo clippy -- -Wclippy::all
  - cargo fmt -- --check
  - cargo run -- dump -a
