language: rust

os:
  - linux


before_install:
  - rustup component add clippy rustfmt


install:
  - cargo clippy -- -Wclippy::all
  - cargo fmt -- --check
  - cargo test --all-features
  - cargo run -- dump -jp --memory --network
