[package]
name = "rsys-cli"
version = "0.1.0"
authors = ["wojciechkepka <wojtek.kepka@protonmail.com>"]
edition = "2018"

[dependencies]
rsys = { version = "0.4", path = "../rsys", features = ["serialize"] }
structopt = { version = "0.3", default-features = false }
serde_json = "1"
serde = "1"


[[bin]]
name = "rsys"
path = "./src/main.rs"
